### ISSUE TITLE
Crash during MG for stanford.arithmetic

### ISSUE THREAD

**Issue by arr28** [SteveDraper/ggp-base#153]
```
[GamePlayer] java.lang.NullPointerException
	at org.ggp.base.util.propnet.polymorphic.factory.OptimizingPolymorphicPropNetFactory.removeIrrelevantBasesAndInputs(OptimizingPolymorphicPropNetFactory.java:1590)
	at org.ggp.base.util.statemachine.implementation.propnet.forwardDeadReckon.ForwardDeadReckonPropnetStateMachine.initialize(ForwardDeadReckonPropnetStateMachine.java:1358)
	at org.ggp.base.player.gamer.statemachine.sancho.StateMachineProxy.initialize(StateMachineProxy.java:41)
	at org.ggp.base.player.gamer.statemachine.StateMachineGamer.metaGame(StateMachineGamer.java:201)
	at org.ggp.base.player.request.grammar.StartRequest.process(StartRequest.java:71)
	at org.ggp.base.player.GamePlayer.run(GamePlayer.java:110)
```

**Comment by arr28** [comment]
There's no sensible way to cope with GDL that's broken like this.  I've simply added a log to make it clear what the problem is.

```08:55:59.855 ! Invalid GDL.  No goals defined for our role (player)!  We will crash.```
